//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHoteleria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRegistroLimpiezas
    {
        public int idDetRegLim { get; set; }
        public string idEmpleado { get; set; }
        public string idRegistroLimpieza { get; set; }
        public string idHabitacion { get; set; }
    }
}
