//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHoteleria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public string idHabitacion { get; set; }
        public string caracteristicas { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> nroPiso { get; set; }
        public Nullable<int> nroCamas { get; set; }
        public string estado { get; set; }
    }
}
