//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHoteleria.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public string idServicio { get; set; }
        public Nullable<bool> wifiLobby { get; set; }
        public Nullable<bool> wifiHabitacion { get; set; }
        public Nullable<bool> alberca { get; set; }
        public Nullable<bool> spa { get; set; }
        public Nullable<bool> estacionamiento { get; set; }
        public Nullable<bool> mascotas { get; set; }
        public Nullable<bool> aireAcondicionado { get; set; }
        public Nullable<bool> restaurante { get; set; }
        public Nullable<bool> barHotel { get; set; }
        public Nullable<bool> gym { get; set; }
    }
}
